### PR TITLE
Update package name to flower

### PR DESCRIPTION
**Pull request by marjanAlbouye**
This PR updates all the references to the package name, changing from `jankflow` to `flower`.

Second update: Change `flower` to `flowerMD`.

### CODE REVIEW

**Review by chrisjonesBSU — APPROVED** [review]
LGTM. We're having that same test fail trying to find the table txt file last time we did a rename. Do you remember how we fixed it, or did it fix itself after merging?

**Comment by marjanAlbouye** [comment]
> LGTM. We're having that same test fail trying to find the table txt file last time we did a rename. Do you remember how we fixed it, or did it fix itself after merging?

That is caused by gitignore not staging the .txt files. Since the directory containing those files is renamed, I need to add those files manually to be able to commit.

**Review by RainierBarrett — COMMENTED** [review]
Should be good to go once that last test passes 👍

**Comment by RainierBarrett** [comment]
```
   × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/runner/work/flowerMD/flowerMD/setup.py", line 39, in <module>
          with open(os.path.join(here, NAME, "__version__.py")) as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/flowerMD/flowerMD/flowerMD/__version__.py'
      [end of output]
  ```

Pretty sure this error is caused by one dir name being `flowerMD` and one being `flowermd`

**Pull request merged**
